version: '2'
services:
    myretailproducts-app:
        image: myretailproducts
        external_links:
            - myretailproducts-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=MyRetailProducts
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myretailproducts-mongodb:
        extends:
            file: mongodb.yml
            service: myretailproducts-mongodb
